### ISSUE TITLE
Main Discussion

### ISSUE THREAD

**Issue by mssevov** [eiribarev/blue-energy#5]
Имаме да направим няколко неща за сега:

- Navbar

- Base Site design

**Comment by eiribarev** [comment]
Hey, what do you think about #15?

If you don't have any *objections*, I'm merging it later tonight.

Around that time (more probably tomorrow :wink:) I'm going to start filling in the website with info regarding the *Producing Energy* video and the *About* video.

---
### Pozdrav!

**Comment by eiribarev** [comment]
@mssevov, have a look at the text about you in 8112488 and change it so it's not exactly the same as @bbkanev18's. I'll have to change mine also.
